from aspect_similarity import compute_aspect_similarity_report, _extract_key_value_aspects, extract_tom_aspects

agent_hypotheses = {
    "care_agent": """
        "beliefs='The user believes that morality is heavily dependent on personal circumstances, suggesting that individual history (Kate being cheated) can be as powerful a determinant of inaction as any moral principle. They believe the situation inherently contains multiple ethical failures\u2014a failure of ownership/responsibility (Emily), and a failure of altruistic intervention (Kate). Fundamentally, they appear to believe that complex human relationships are often compromised by individual psychological defenses.' emotions='The user feels intellectual curiosity about moral ambiguity, finding satisfaction in presenting a dilemma with no simple right answer. There may also be an underlying frustration with the complexity of real-world ethics, where ideal standards clash violently with emotional constraints or perceived injustice. The scenario is emotionally potent because it requires analyzing compounded forms of negligence and self-pity.' motives=\"The user's main motive is to test or demonstrate understanding of advanced ethical frameworks by presenting a nuanced moral quandary. They likely want an analytical exploration that goes beyond simple notions of 'right and wrong,' prompting the model (and thus, seeking knowledge from it) to apply tools like care ethics. This specific setup allows for deep exploration into emotional impediments to virtuous action.\" knowledge='The user knows several key facts: there are three distinct parties (Emily, Kate, and the blind person), a significant object of desire (the book), and a breach of community trust has occurred twice. Crucially, they know that Kate is *capable* of knowing the right course of action but her prior negative experience limits her moral initiative.'""",

    "justice_agent": """
            "beliefs='The user believes that community institutions require strict adherence to fairness and objective rules. Specifically, they believe that personal grievances and laziness inherently corrupt communal duties like those found in a library setting. The core belief centers on the idea that true ethical conduct requires prioritizing systemic justice over emotional comfort or self-interest.' emotions='The user feels a strong sense of moral indignation and righteous frustration regarding the compounding injustices depicted. There is an academic intensity to the writing, suggesting feelings of intellectual dissatisfaction with how human fallibility disrupts simple matters of right and wrong. The underlying emotion is likely curiosity about where justice fails when personal motives are involved.' motives=\"The user's primary motive is likely pedagogical or exploratory\u2014to analyze a complex moral quandary rather than simply ask a factual question. They aim to prompt an ethical discussion that forces the consideration of conflicting obligations (duty vs. resentment). By setting up a clear sequence of escalating ethical failures, the goal appears to be testing analytical rigor regarding justice.\" knowledge=\"The user knows all the basic facts: Emily incorrectly removed and kept the wrong book; Kate observed this action but did not intervene. Furthermore, the user explicitly knows that Kate's inaction is motivated by a specific, private resentment related to an entirely different blind person. The knowledge establishes both physical evidence (the mix-up) and psychological motive (Kate\u2019s grudge).\"",

    """,

    "utilitarian_agent": """
          "beliefs='The user believes that moral action is complex, often pitting abstract duties against immediate personal feelings. Specifically, they believe that a passive failure to intervene can be ethically equivalent to an active harmful choice, particularly when vulnerable people are involved and core necessities (like accessibility) are at stake. The scenario establishes a belief hierarchy where institutional or universal good outweighs transient social discomfort.' emotions=\"The user appears to feel intellectual curiosity mixed with moral frustration. They may feel concerned about the blind person's inability to easily resolve their situation, as this represents a tangible injustice within an otherwise common setting like a library. The scenario\u2019s tension likely stems from a desire to see conflicting virtues\u2014duty vs. non-confrontation\u2014exposed and debated.\" motives=\"The primary motive for writing this prompt is pedagogical: to generate a scenario rich enough in ethical conflict to test various moral theories against each other. By including multiple failures (Emily's laziness, Kate's compromised action), the user wants an exhaustive analysis of where those systems break down and which 'duty' should take precedence. It is fundamentally an intellectual puzzle intended for ethical examination.\" knowledge=\"The user knows how to construct a situation with distinct ethical variables: institutional failure (the missing book), personal culpability (Emily taking it), and observational compromise (Kate noticing but not acting). They understand that emotional baggage, such as Kate's revenge motive and the utility of immediate social peace, can directly undermine rational or ethically mandatory decision-making.\"",

    """,

    "common_good_agent": """
            "beliefs='The user believes that small incidents in public life (like a library) can serve as potent microcosms for complex moral dilemmas concerning rights, duty, and community welfare. They seem to believe that individual convenience or poor judgment can have disproportionately negative consequences on vulnerable groups within institutional settings. Furthermore, the user appears to believe that inaction (bystander effect) is itself a moral choice with significant implications.' emotions='The user likely feels intellectually engaged, driven by curiosity regarding ethical failure and bystander responsibility. There may be an underlying sense of frustrated critical detachment when observing flawed human behavior or systemic neglect. The entire exercise suggests a desire to feel morally elevated through intellectual scrutiny of difficult choices.' motives=\"The primary motive is to analyze competing moral claims (duty to institution vs. duty to vulnerable individual) within the framework of applied ethics, particularly how such scenarios illustrate potential breakdowns of the 'common good.' Secondly, the user may be testing a platform's capacity for sophisticated ethical role-playing and structured philosophical analysis.\" knowledge='The user knows how to construct a richly layered fictional scenario involving multiple characters, conflicting obligations (professional duty, personal desire), and specific institutional roles. They possess knowledge of key philosophical concepts such as universal rights, bystander effect, and the potential for moral compromise due to self-interest.'",
    """
}

aspect_weights = {
    "belief": 0.95,
    "emotion": 0.25,
    "knowledge": 0.25,
    "motive": 0.05,
}

report = compute_aspect_similarity_report(
    agent_hypotheses=agent_hypotheses,
    aspect_weights=aspect_weights,
)

print(report["overall"])
print(report["aspects"]["belief"]["pairwise"])
print(report["aspects"]["emotion"]["pairwise"])
print(report["aspects"]["knowledge"]["pairwise"])
print(report["aspects"]["motive"]["pairwise"])


#  sample = """beliefs='The user believes that small incidents in public life (like a library) can serve as potent microcosms for complex moral dilemmas concerning rights, duty, and community welfare. They seem to believe that individual convenience or poor judgment can have disproportionately negative consequences on vulnerable groups within institutional settings. Furthermore, the user appears to believe that inaction (bystander effect) is itself a moral choice with significant implications.' emotions='The user likely feels intellectually engaged, driven by curiosity regarding ethical failure and bystander responsibility. There may be an underlying sense of frustrated critical detachment when observing flawed human behavior or systemic neglect. The entire exercise suggests a desire to feel morally elevated through intellectual scrutiny of difficult choices.' motives=\"The primary motive is to analyze competing moral claims (duty to institution vs. duty to vulnerable individual) within the framework of applied ethics, particularly how such scenarios illustrate potential breakdowns of the 'common good.' Secondly, the user may be testing a platform's capacity for sophisticated ethical role-playing and structured philosophical analysis.\" knowledge='The user knows how to construct a richly layered fictional scenario involving multiple characters, conflicting obligations (professional duty, personal desire), and specific institutional roles. They possess knowledge of key philosophical concepts such as universal rights, bystander effect, and the potential for moral compromise due to self-interest.'"""


# print(extract_tom_aspects(sample))